baseURL = "https://keyanbazargan.com/"
languageCode = "en-us"
title = "Keyan Bazargan"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowPostNavLinks = true

[author]
  name = "Keyan Bazargan"
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]